pythonExam/blog/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.home, name='home'),
    path('post/new/', views.blog_post_create, name='blog_post_create'),
    path('post/<int:pk>/', views.blog_post_detail, name='blog_post_detail'),
    path('post/<int:pk>/edit/', views.blog_post_edit, name='blog_post_edit'),
    path('post/<int:pk>/delete/', views.blog_post_delete, name='blog_post_delete'),
]

pythonExam/exam_blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from blog import views

app_name = 'blog'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path('', views.home, name='home'),
    path('login/', LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('post/<int:pk>/', views.blog_post_detail, name='blog_post_detail'),
    path('post/new/', views.blog_post_create, name='blog_post_create'),
    path('post/<int:pk>/edit/', views.blog_post_edit, name='blog_post_edit'),
    path('post/<int:pk>/delete/', views.blog_post_delete, name='blog_post_delete'),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonExam/blog/models.py


from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    image = models.ImageField(upload_to='blog/images/', null=True, blank=True)
    video = models.FileField(upload_to='blog/videos/', null=True, blank=True)

    def __str__(self):
        return self.title



class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    bio = models.TextField(blank=True)
    objects = CustomUserManager()

    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name ='groups',
        blank = True,
        help_text ='The groups this user belongs to.',
        related_name ='customuser_set',  # Add this line
        related_query_name ='user',
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name ='user permissions',
        blank = True,
        help_text ='Specific permissions for this user.',
        related_name ='customuser_set',  # Add this line
        related_query_name ='user',
    )

    def __str__(self):
        return self.username

pythonExam/blog/forms.py
from django import forms
from .models import BlogPost
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'author', 'content', 'image', 'video']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'username', 'bio')

pythonExam/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib import messages
import logging
from .models import BlogPost
from .forms import BlogPostForm
from .forms import CustomUserCreationForm

logger = logging.getLogger(__name__)


def home(request):
    blog_posts = BlogPost.objects.all()
    return render(request, 'blog/home.html', {'blog_posts': blog_posts})

def blog_post_create(request):
    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            blog_post = form.save()
            return redirect('blog:home')
    else:
        form = BlogPostForm()
    return render(request, 'blog/blog_post_form.html', {'form': form})

def blog_post_detail(request, pk):
    blog_post = get_object_or_404(BlogPost, pk=pk)
    return render(request, 'blog/blog_post_detail.html', {'blog_post': blog_post})

def blog_post_edit(request, pk):
    blog_post = get_object_or_404(BlogPost, pk=pk)
    if request.method == 'POST':
        form = BlogPostForm(request.POST, request.FILES, instance=blog_post)
        if form.is_valid():
            blog_post = form.save()
            return redirect('blog_post_detail', pk=blog_post.pk)
    else:
        form = BlogPostForm(instance=blog_post)
    return render(request, 'blog/blog_post_form.html', {'form': form})

def blog_post_delete(request, pk):
    blog_post = get_object_or_404(BlogPost, pk=pk)
    if request.method == 'POST':
        blog_post.delete()
        return redirect('blog:home')
    return render(request, 'blog/blog_post_confirm_delete.html', {'blog_post': blog_post})


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # Log the user in after registration
            logger.info(f"User {user.username} successfully registered.")
            return redirect('blog:home')
        else:
            logger.error(f"Registration failed. Form errors: {form.errors}")
    else:
        form = CustomUserCreationForm()

    return render(request, 'blog/register.html', {'form': form})

pythonExam/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <!--link rel="stylesheet" type="text/css" href="{% static 'blog/styles.css' %}"-->
    <link rel="stylesheet" type="text/css" href="{% static 'blog/styles_blog.css' %}">
</head>
<body>
    <div id="content">
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
        {% block content %}{% endblock %}
    </div>
</body>
</html>

pythonExam/blog/templates/blog/blog_post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block title %}Confirm Deletion{% endblock %}

{% block content %}
    <h1>Confirm Deletion</h1>
    <p>Are you sure you want to delete the blog post "{{ blog_post.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, delete</button>
    </form>
    <a href="{% url 'blog:home' %}">No, cancel</a>
{% endblock %}

pythonExam/blog/templates/blog/blog_post_detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ blog_post.title }}{% endblock %}

{% block content %}
    <h1>{{ blog_post.title }}</h1>
    <p>Author: {{ blog_post.author }}</p>
    <p>Created On: {{ blog_post.created_on }}</p>
    <p>Updated On: {{ blog_post.updated_on }}</p>
    <p>{{ blog_post.content }}</p>

    {% if blog_post.image %}
        <img src="{{ blog_post.image.url }}" alt="Post Image">
    {% endif %}

    {% if blog_post.video %}
        <video controls>
            <source src="{{ blog_post.video.url }}" type="video/mp4">
        </video>
    {% endif %}

    <a href="{% url 'blog:home' %}">Back to Home</a>
{% endblock %}

pythonExam/blog/templates/blog/blog_post_form.html
{% extends 'blog/base.html' %}

{% block title %}{% if form.instance.pk %}Edit{% else %}Create{% endif %} Blog Post{% endblock %}

<div id="content" class="form-container">
{% block content %}
    <h1>{% if form.instance.pk %}Edit{% else %}Create{% endif %} Blog Post</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
    <a href="{% url 'blog:home' %}">Cancel</a>
{% endblock %}
</div>

pythonExam/blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block title %}Welcome to the Cat Blog{% endblock %}

{% block content %}
    <div class="container">
        <h1>Welcome to the Cat Blog</h1>

        {% if user.is_authenticated %}
        <p><h2><a href="{% url 'blog:blog_post_create' %}">Create a New Post</a></h2></p>
    </br></br>
        <ul class="post-list">
            {% for post in blog_posts %}
                <li class="post-item">
                    <h1>{{ post.title }}</h1>
                    <a href="{% url 'blog:blog_post_edit' pk=post.pk %}">Edit</a>
                    <a href="{% url 'blog:blog_post_delete' pk=post.pk %}">Delete</a>
                    <p>Author: {{ post.author }}</p>
                    <p>Published on: {{ post.created_on }}</p>
                    <p>{{ post.content }}</p>
                    

                    {% if post.image %}
                        <img src="{{ post.image.url }}" alt="Post Image" class="post-image">
                    {% endif %}

                    {% if post.video %}
                        <video controls class="post-video">
                            <source src="{{ post.video.url }}" type="video/mp4">
                        </video>
                    {% endif %}
                    
                </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>You are not logged in. Please log in or register.</p>
    <ul>
      <li><a href="{% url 'blog:login' %}">Login</a></li>
      <li><a href="{% url 'blog:register' %}">Register</a></li>
    </ul>
  {% endif %}
    </div>
{% endblock %}

pythonExam/blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <h2>Login</h2>
    <form method="post" action="{% url 'blog:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

pythonExam/blog/templates/blog/logout.html
{% extends 'blog/base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}
  <h2>Logout</h2>
  <p>You have been successfully logged out.</p>
  <p>Return to <a href="{% url 'blog:home' %}">Home</a>.</p>
{% endblock %}

pythonExam/blog/templates/blog/register.html
{% extends 'blog/base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
  <h2>Register</h2>
  <form method="post" action="{% url 'blog:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    {% if form.errors %}
        <p style="color: red;">Please correct the errors below.</p>
    {% endif %}
    <button type="submit">Register</button>
  </form>
  {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}